//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientForWcfSevice.StudentListService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/StudentWcfService")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AvgMarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float AvgMark {
            get {
                return this.AvgMarkField;
            }
            set {
                if ((this.AvgMarkField.Equals(value) != true)) {
                    this.AvgMarkField = value;
                    this.RaisePropertyChanged("AvgMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mycompany.com/wcf", ConfigurationName="StudentListService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/wcf/IService1/GetStudentsGraterThan", ReplyAction="http://mycompany.com/wcf/IService1/GetStudentsGraterThanResponse")]
        ClientForWcfSevice.StudentListService.Student[] GetStudentsGraterThan(float mark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/wcf/IService1/GetStudentsGraterThan", ReplyAction="http://mycompany.com/wcf/IService1/GetStudentsGraterThanResponse")]
        System.Threading.Tasks.Task<ClientForWcfSevice.StudentListService.Student[]> GetStudentsGraterThanAsync(float mark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/wcf/IService1/GetStudentsLowerThan", ReplyAction="http://mycompany.com/wcf/IService1/GetStudentsLowerThanResponse")]
        ClientForWcfSevice.StudentListService.Student[] GetStudentsLowerThan(float mark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/wcf/IService1/GetStudentsLowerThan", ReplyAction="http://mycompany.com/wcf/IService1/GetStudentsLowerThanResponse")]
        System.Threading.Tasks.Task<ClientForWcfSevice.StudentListService.Student[]> GetStudentsLowerThanAsync(float mark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/wcf/IService1/GetStudentsInRange", ReplyAction="http://mycompany.com/wcf/IService1/GetStudentsInRangeResponse")]
        ClientForWcfSevice.StudentListService.Student[] GetStudentsInRange(float minMark, float maxMark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/wcf/IService1/GetStudentsInRange", ReplyAction="http://mycompany.com/wcf/IService1/GetStudentsInRangeResponse")]
        System.Threading.Tasks.Task<ClientForWcfSevice.StudentListService.Student[]> GetStudentsInRangeAsync(float minMark, float maxMark);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientForWcfSevice.StudentListService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientForWcfSevice.StudentListService.IService1>, ClientForWcfSevice.StudentListService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientForWcfSevice.StudentListService.Student[] GetStudentsGraterThan(float mark) {
            return base.Channel.GetStudentsGraterThan(mark);
        }
        
        public System.Threading.Tasks.Task<ClientForWcfSevice.StudentListService.Student[]> GetStudentsGraterThanAsync(float mark) {
            return base.Channel.GetStudentsGraterThanAsync(mark);
        }
        
        public ClientForWcfSevice.StudentListService.Student[] GetStudentsLowerThan(float mark) {
            return base.Channel.GetStudentsLowerThan(mark);
        }
        
        public System.Threading.Tasks.Task<ClientForWcfSevice.StudentListService.Student[]> GetStudentsLowerThanAsync(float mark) {
            return base.Channel.GetStudentsLowerThanAsync(mark);
        }
        
        public ClientForWcfSevice.StudentListService.Student[] GetStudentsInRange(float minMark, float maxMark) {
            return base.Channel.GetStudentsInRange(minMark, maxMark);
        }
        
        public System.Threading.Tasks.Task<ClientForWcfSevice.StudentListService.Student[]> GetStudentsInRangeAsync(float minMark, float maxMark) {
            return base.Channel.GetStudentsInRangeAsync(minMark, maxMark);
        }
    }
}
